sudo: false
language: node_js
node_js:
  - 6
services:
  - couchdb
git:
  depth: 30
after_success:
  - npm run semantic-release
env:
  matrix:
  - COUCH_HOST=http://localhost:5984
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
